import type { SkillContract } from '@agi-os/skills';

export const FILESYSTEM_READ_CONTRACT: SkillContract = {
  id: 'filesystem.read',
  name: 'Read File',
  version: '1.0.0',
  description: 'Read content from a file',
  category: 'filesystem',
  capabilities: ['read'],
  risk: 'LOW',
  requiresApproval: false,
  requiresNetwork: false,
  requiresPersistence: false,
  allowedScopes: ['filesystem.read'],
  timeoutMs: 10000,
  retryLimit: 3,
  verification: { required: false, level: 'BASIC' },
  inputSchema: { type: 'object', required: ['path'] },
  outputSchema: { type: 'object', properties: { content: { type: 'string' } } },
};

export const FILESYSTEM_LIST_CONTRACT: SkillContract = {
  id: 'filesystem.list',
  name: 'List Directory',
  version: '1.0.0',
  description: 'List files and directories',
  category: 'filesystem',
  capabilities: ['list'],
  risk: 'LOW',
  requiresApproval: false,
  requiresNetwork: false,
  requiresPersistence: false,
  allowedScopes: ['filesystem.read'],
  timeoutMs: 10000,
  retryLimit: 3,
  verification: { required: false, level: 'BASIC' },
  inputSchema: { type: 'object', required: ['path'] },
  outputSchema: { type: 'object', properties: { entries: { type: 'array' } } },
};

export const FILESYSTEM_WRITE_CONTRACT: SkillContract = {
  id: 'filesystem.write',
  name: 'Write File',
  version: '1.0.0',
  description: 'Write content to a file',
  category: 'filesystem',
  capabilities: ['write'],
  risk: 'MEDIUM',
  requiresApproval: false,
  requiresNetwork: false,
  requiresPersistence: false,
  allowedScopes: ['filesystem.write'],
  timeoutMs: 10000,
  retryLimit: 3,
  verification: { required: false, level: 'BASIC' },
  inputSchema: { type: 'object', required: ['path', 'content'] },
  outputSchema: { type: 'object', properties: { bytesWritten: { type: 'number' } } },
};

export const TEXT_SUMMARIZE_CONTRACT: SkillContract = {
  id: 'text.summarize',
  name: 'Summarize Text',
  version: '1.0.0',
  description: 'Summarize text using LLM',
  category: 'core',
  capabilities: ['summarize'],
  risk: 'LOW',
  requiresApproval: false,
  requiresNetwork: false,
  requiresPersistence: false,
  allowedScopes: ['llm.complete'],
  timeoutMs: 30000,
  retryLimit: 3,
  verification: { required: false, level: 'BASIC' },
  inputSchema: { type: 'object', required: ['text'] },
  outputSchema: { type: 'object', properties: { summary: { type: 'string' } } },
};

export const MISSION_REPORT_CONTRACT: SkillContract = {
  id: 'mission.report',
  name: 'Mission Report',
  version: '1.0.0',
  description: 'Generate mission status report',
  category: 'core',
  capabilities: ['report'],
  risk: 'LOW',
  requiresApproval: false,
  requiresNetwork: false,
  requiresPersistence: false,
  allowedScopes: ['mission.read'],
  timeoutMs: 10000,
  retryLimit: 1,
  verification: { required: false, level: 'BASIC' },
  inputSchema: { type: 'object', required: ['missionId'] },
  outputSchema: { type: 'object', properties: { report: { type: 'string' } } },
};
